sudo: required
services:
  - docker

before_install:
  - docker build -t adrianhiu/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true adrianhiu/docker-react npm run test
deploy: 
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "test"
  env: "Test-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-656124236591"
  bucket_path: "test"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"